name: Manual Workflow
on:
  workflow_dispatch: # Triggered manually
    inputs:
      PublisherId:
        description: "The ID of the publisher"
        required: true
      DevToken:
        description: "Your DevToken"
        required: true
      Username: # Add this input
        description: "Your username"
        required: true
      Password: # Add this input
        description: "Your password"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Input provided
        run: echo "PublisherId=${{ github.event.inputs.PublisherId }}"
        env:
          PUBLISHER_ID: ${{ github.event.inputs.PublisherId }}
      - name: Run Python Script
        run: python src/simple.py
      - name: Save Output to File
        run: |
          python src/simple.py > output.txt
        # The above line redirects the script output to a file named "output.txt"
        # Adjust the filename as needed
      - name: Upload Output File
        uses: actions/upload-artifact@v2
        with:
          name: my-output-artifact
          path: output.txt
