name: Manual Workflow
on:
  workflow_dispatch: # Triggered manually
    inputs:
      API_URL:
        description: "The ID of the API"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Input provided
        run: echo "PublisherId=${{ github.event.inputs.PublisherId }}"
        env:
          PUBLISHER_ID: ${{ secrets.PUBLISHER_ID }}
      - name: Run Python Script
        run: python src/simple.py
