name: Manual Workflow
on:
  workflow_dispatch: # Triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Prompt for PublisherId
        run: |
          echo "Please enter the PublisherId:"
          read PublisherId
          echo "You entered PublisherId=$PublisherId"
      - name: Say Hello to the World
        run: echo "Hello, World! PublisherId=$PublisherId"
        env:
          PUBLISHER_ID: ${{ secrets.PUBLISHER_ID }}
