name: Manual Workflow
on:
  workflow_dispatch: # Triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Say Hello to the World
        run: echo "Hello, World! PublisherId=${{ github.event.inputs.PublisherId }}"
        env:
          PUBLISHER_ID: ${{ secrets.PUBLISHER_ID }}
      - name: Run Python Script
        run: python playwrightScript.py
