name: Manual Workflow
on:
  workflow_dispatch: # Triggered manually
    inputs:
      PublisherId:
        description: "The ID of the publisher"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Input provided
        run: echo "PublisherId=${{ github.event.inputs.PublisherId }}"
        env:
          PUBLISHER_ID: ${{ github.event.inputs.PublisherId }}
      - name: Set environment variable
        env:
          API_URL: ${{ secrets.PublisherId }}
        run: |
          echo "API_URL=$API_URL" >> $GITHUB_ENV
      - name: Run Python Script
        run: python src/simple.py
